import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:path_provider/path_provider.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import '../models/usage_entry.dart';
import '../services/usage_tracking_service.dart';
import '../screens/usage_analytics_screen.dart';

class QuickSummaryBottomSheet extends StatefulWidget {
  final String childId;
  final String childName;
  
  const QuickSummaryBottomSheet({
    super.key,
    required this.childId,
    required this.childName,
  });

  @override
  State<QuickSummaryBottomSheet> createState() => _QuickSummaryBottomSheetState();
}

class _QuickSummaryBottomSheetState extends State<QuickSummaryBottomSheet> {
  final UsageTrackingService _service = UsageTrackingService();
  final ScreenshotController _screenshotController = ScreenshotController();
  bool _isLoading = true;
  Map<String, dynamic> _data = {};
  
  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    setState(() => _isLoading = true);
    final data = await _service.getAutomaticQuickSummaryData(widget.childId);
    setState(() {
      _data = data;
      _isLoading = false;
    });
  }

  String _formatDuration(int minutes) {
    if (minutes < 60) return '$minutes min';
    final hours = minutes ~/ 60;
    final mins = minutes % 60;
    return mins > 0 ? '${hours}h ${mins}m' : '${hours}h';
  }

  Color _getWellnessColor(int score) {
    if (score >= 80) return Colors.green;
    if (score >= 60) return Colors.orange;
    return Colors.red;
  }

  String _getWellnessLabel(int score) {
    if (score >= 80) return 'Excellent';
    if (score >= 60) return 'Good';
    if (score >= 40) return 'Fair';
    return 'Needs Attention';
  }

  Future<void> _shareReportCard() async {
    try {
      final Uint8List? image = await _screenshotController.capture();
      if (image != null) {
        final directory = await getApplicationDocumentsDirectory();
        final fileName = 'daily_report_${widget.childName}_${DateTime.now().toIso8601String().split('T')[0]}.png';
        final file = File('${directory.path}/$fileName');
        await file.writeAsBytes(image);
        
        await Share.shareXFiles(
          [XFile(file.path)],
          text: '📊 ${widget.childName}\'s Daily Screen Time Report - ${DateTime.now().toString().split(' ')[0]}\n\nGenerated by STR App',
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error sharing: $e')),
        );
      }
    }
  }

  Future<void> _exportToPDF() async {
    Navigator.pop(context);
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => UsageAnalyticsScreen(
          childId: widget.childId,
          childName: widget.childName,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height * 0.9,
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                // Handle bar
                Container(
                  margin: const EdgeInsets.only(top: 12, bottom: 8),
                  width: 40,
                  height: 4,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade300,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
                
                // Header with live indicator
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              Text(
                                'Daily Summary',
                                style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                                      fontWeight: FontWeight.bold,
                                    ),
                              ),
                              if (_data['isCurrentlyActive'] == true) ...[
                                const SizedBox(width: 8),
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                  decoration: BoxDecoration(
                                    color: Colors.red,
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: const Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      Icon(Icons.circle, color: Colors.white, size: 8),
                                      SizedBox(width: 4),
                                      Text(
                                        'LIVE',
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 12,
                                          fontWeight: FontWeight.bold,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ],
                          ),
                          Text(
                            '${widget.childName} • ${DateFormat('MMM dd, yyyy').format(DateTime.now())}',
                            style: TextStyle(color: Colors.grey.shade600),
                          ),
                        ],
                      ),
                      Row(
                        children: [
                          IconButton(
                            icon: const Icon(Icons.refresh),
                            onPressed: _loadData,
                            tooltip: 'Refresh',
                          ),
                          IconButton(
                            icon: const Icon(Icons.close),
                            onPressed: () => Navigator.pop(context),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                
                // Scrollable content
                Expanded(
                  child: Screenshot(
                    controller: _screenshotController,
                    child: SingleChildScrollView(
                      padding: const EdgeInsets.all(20),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // Hero Section
                          _buildHeroSection(),
                          
                          const SizedBox(height: 20),
                          
                          // Currently Active Card (if active)
                          if (_data['isCurrentlyActive'] == true)
                            _buildCurrentlyActiveCard(),
                          
                          if (_data['isCurrentlyActive'] == true)
                            const SizedBox(height: 20),
                          
                          // AI Insight Card
                          _buildAIInsightCard(),
                          
                          const SizedBox(height: 20),
                          
                          // Category Breakdown
                          _buildCategoryBreakdown(),
                          
                          const SizedBox(height: 20),
                          
                          // Hourly Heatmap
                          _buildHourlyHeatmap(),
                          
                          const SizedBox(height: 20),
                          
                          // Top Apps with Icons
                          _buildTopApps(),
                          
                          const SizedBox(height: 20),
                          
                          // Session Stats
                          _buildSessionStats(),
                          
                          const SizedBox(height: 20),
                          
                          // Comparison Stats
                          _buildComparisonStats(),
                          
                          const SizedBox(height: 30),
                          
                          // Share/Export Buttons
                          _buildActionButtons(),
                          
                          const SizedBox(height: 20),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
    );
  }

  Widget _buildHeroSection() {
    final total = _data['totalMinutes'] ?? 0;
    final score = _data['wellnessScore'] ?? 0;
    final color = _getWellnessColor(score);
    final dailyLimit = _data['dailyLimit'] ?? 120;
    final percentage = (total / dailyLimit).clamp(0.0, 1.0);
    
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [color.withOpacity(0.2), color.withOpacity(0.05)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withOpacity(0.3), width: 2),
      ),
      child: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Total Screen Time',
                      style: TextStyle(fontSize: 14, color: Colors.grey, fontWeight: FontWeight.w500),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      _formatDuration(total),
                      style: TextStyle(
                        fontSize: 42,
                        fontWeight: FontWeight.bold,
                        color: color,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      '${_data['entryCount'] ?? 0} sessions • Limit: ${_formatDuration(dailyLimit)}',
                      style: TextStyle(fontSize: 13, color: Colors.grey.shade600),
                    ),
                  ],
                ),
              ),
              Column(
                children: [
                  Container(
                    width: 90,
                    height: 90,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Colors.white,
                      border: Border.all(color: color, width: 4),
                      boxShadow: [
                        BoxShadow(
                          color: color.withOpacity(0.3),
                          blurRadius: 10,
                          spreadRadius: 2,
                        ),
                      ],
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(
                          '$score',
                          style: TextStyle(
                            fontSize: 28,
                            fontWeight: FontWeight.bold,
                            color: color,
                          ),
                        ),
                        Text(
                          'Score',
                          style: TextStyle(fontSize: 11, color: color.withOpacity(0.8)),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 8),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                    decoration: BoxDecoration(
                      color: color.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Text(
                      _getWellnessLabel(score),
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: color,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: 16),
          // Progress bar for daily limit
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Daily Limit Progress',
                    style: TextStyle(fontSize: 12, color: Colors.grey.shade600),
                  ),
                  Text(
                    '${(percentage * 100).round()}%',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                      color: total > dailyLimit ? Colors.red : Colors.green,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              ClipRRect(
                borderRadius: BorderRadius.circular(10),
                child: LinearProgressIndicator(
                  value: percentage,
                  backgroundColor: Colors.grey.shade200,
                  valueColor: AlwaysStoppedAnimation<Color>(
                    total > dailyLimit ? Colors.red : color,
                  ),
                  minHeight: 10,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildCurrentlyActiveCard() {
    final currentApp = _data['currentApp'] as String? ?? 'Unknown App';
    final appName = _service.getAppDisplayName(currentApp, currentApp);
    final icon = _service.getAppIcon(currentApp);
    final color = _service.getAppColor(currentApp);
    
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.red.shade50,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.red.shade200),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(icon, color: color, size: 28),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      width: 8,
                      height: 8,
                      decoration: const BoxDecoration(
                        color: Colors.red,
                        shape: BoxShape.circle,
                      ),
                    ),
                    const SizedBox(width: 8),
                    const Text(
                      'Currently Active',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        color: Colors.red,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 4),
                Text(
                  appName,
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                Text(
                  'Screen is on now',
                  style: TextStyle(
                    fontSize: 12,
                    color: Colors.grey.shade600,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAIInsightCard() {
    final insight = _data['aiInsight'] ?? 'No insight available';
    IconData insightIcon = Icons.lightbulb;
    Color insightColor = Colors.blue;
    
    if (insight.contains('⚠️') || insight.contains('violation')) {
      insightIcon = Icons.warning;
      insightColor = Colors.orange;
    } else if (insight.contains('🌟') || insight.contains('Excellent')) {
      insightIcon = Icons.star;
      insightColor = Colors.green;
    } else if (insight.contains('📱') && insight.contains('active')) {
      insightIcon = Icons.phone_android;
      insightColor = Colors.purple;
    }
    
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: insightColor.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border(left: BorderSide(color: insightColor, width: 4)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(insightIcon, color: insightColor, size: 20),
              const SizedBox(width: 8),
              Text(
                'AI Insight',
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  color: insightColor.withOpacity(0.9),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            insight,
            style: TextStyle(
              color: Colors.grey.shade800,
              height: 1.5,
              fontSize: 14,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCategoryBreakdown() {
    final edu = _data['educational'] ?? 0;
    final ent = _data['entertainment'] ?? 0;
    final util = _data['utility'] ?? 0;
    final total = edu + ent + util;
    
    if (total == 0) return const SizedBox.shrink();
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Content Breakdown',
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 16),
        _buildCategoryBar('Educational', edu, total, Colors.green, '🎓', Icons.school),
        const SizedBox(height: 12),
        _buildCategoryBar('Entertainment', ent, total, Colors.orange, '🎮', Icons.videogame_asset),
        const SizedBox(height: 12),
        _buildCategoryBar('Utility', util, total, Colors.blue, '🔧', Icons.build),
      ],
    );
  }

  Widget _buildCategoryBar(String label, int value, int total, Color color, String emoji, IconData icon) {
    final percentage = total > 0 ? (value / total * 100).round() : 0;
    
    return Row(
      children: [
        Container(
          padding: const EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: color.withOpacity(0.1),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(icon, color: color, size: 20),
        ),
        const SizedBox(width: 12),
        Expanded(
          flex: 2,
          child: Text(
            label,
            style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 15),
          ),
        ),
        Expanded(
          flex: 5,
          child: ClipRRect(
            borderRadius: BorderRadius.circular(10),
            child: LinearProgressIndicator(
              value: total > 0 ? value / total : 0,
              backgroundColor: Colors.grey.shade200,
              valueColor: AlwaysStoppedAnimation<Color>(color),
              minHeight: 14,
            ),
          ),
        ),
        const SizedBox(width: 12),
        SizedBox(
          width: 90,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text(
                '$percentage%',
                style: TextStyle(
                  fontSize: 14, 
                  fontWeight: FontWeight.bold,
                  color: color,
                ),
              ),
              Text(
                _formatDuration(value),
                style: TextStyle(fontSize: 11, color: Colors.grey.shade600),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildHourlyHeatmap() {
    final hourly = _data['hourlyUsage'] as Map<dynamic, dynamic>? ?? {};
    if (hourly.isEmpty) return const SizedBox.shrink();
    
    // Convert to spots for chart
    final spots = <FlSpot>[];
    int maxMinutes = 0;
    for (int hour = 0; hour < 24; hour++) {
      final minutes = hourly[hour] ?? 0;
      spots.add(FlSpot(hour.toDouble(), minutes.toDouble()));
      if (minutes > maxMinutes) maxMinutes = minutes;
    }
    
    // Only show hours with data for cleaner UI
    final activeSpots = spots.where((s) => s.y > 0).toList();
    if (activeSpots.isEmpty) return const SizedBox.shrink();
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text(
              'Hourly Activity',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            Text(
              'Peak usage times',
              style: TextStyle(fontSize: 12, color: Colors.grey.shade600),
            ),
          ],
        ),
        const SizedBox(height: 16),
        SizedBox(
          height: 180,
          child: LineChart(
            LineChartData(
              gridData: FlGridData(
                show: true,
                drawVerticalLine: false,
                horizontalInterval: maxMinutes > 0 ? maxMinutes / 4 : 10,
                getDrawingHorizontalLine: (value) {
                  return FlLine(
                    color: Colors.grey.shade200,
                    strokeWidth: 1,
                  );
                },
              ),
              titlesData: FlTitlesData(
                bottomTitles: AxisTitles(
                  sideTitles: SideTitles(
                    showTitles: true,
                    interval: 4,
                    getTitlesWidget: (value, meta) {
                      final hour = value.toInt();
                      return Padding(
                        padding: const EdgeInsets.only(top: 8),
                        child: Text(
                          '${hour.toString().padLeft(2, '0')}:00',
                          style: TextStyle(
                            fontSize: 11,
                            color: Colors.grey.shade600,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      );
                    },
                  ),
                ),
                leftTitles: AxisTitles(
                  sideTitles: SideTitles(
                    showTitles: true,
                    interval: maxMinutes > 0 ? maxMinutes / 4 : 10,
                    getTitlesWidget: (value, meta) {
                      return Text(
                        '${value.toInt()}m',
                        style: TextStyle(
                          fontSize: 10,
                          color: Colors.grey.shade600,
                        ),
                      );
                    },
                    reservedSize: 40,
                  ),
                ),
                rightTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)),
                topTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)),
              ),
              borderData: FlBorderData(show: false),
              lineBarsData: [
                LineChartBarData(
                  spots: activeSpots,
                  isCurved: true,
                  color: Colors.purple,
                  barWidth: 4,
                  isStrokeCapRound: true,
                  dotData: FlDotData(
                    show: true,
                    getDotPainter: (spot, percent, bar, index) {
                      return FlDotCirclePainter(
                        radius: 4,
                        color: Colors.purple,
                        strokeWidth: 2,
                        strokeColor: Colors.white,
                      );
                    },
                  ),
                  belowBarData: BarAreaData(
                    show: true,
                    color: Colors.purple.withOpacity(0.15),
                  ),
                ),
              ],
              minY: 0,
              maxY: maxMinutes > 0 ? maxMinutes * 1.2 : 10,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildTopApps() {
    final topApps = _data['topApps'] as List<dynamic>? ?? [];
    if (topApps.isEmpty) return const SizedBox.shrink();
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Top Apps Today',
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 12),
        ...topApps.asMap().entries.map((entry) {
          final index = entry.key;
          final app = entry.value as Map<String, dynamic>;
          final package = app['package'] as String? ?? '';
          final name = app['name'] as String? ?? 'Unknown';
          final minutes = app['minutes'] as int? ?? 0;
          final opens = app['opens'] as int? ?? 1;
          final icon = _service.getAppIcon(package);
          final color = _service.getAppColor(package);
          
          return Container(
            margin: const EdgeInsets.only(bottom: 10),
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.grey.shade50,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.grey.shade200),
            ),
            child: Row(
              children: [
                Container(
                  width: 45,
                  height: 45,
                  decoration: BoxDecoration(
                    color: color.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(icon, color: color, size: 24),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        name,
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 15,
                        ),
                      ),
                      Text(
                        '$opens opens • ${app['category'].toString().split('.').last}',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.grey.shade600,
                        ),
                      ),
                    ],
                  ),
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text(
                      _formatDuration(minutes),
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                      ),
                    ),
                    Text(
                      '${(minutes / (_data['totalMinutes'] ?? 1) * 100).round()}% of total',
                      style: TextStyle(
                        fontSize: 11,
                        color: Colors.grey.shade600,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          );
        }).toList(),
      ],
    );
  }

  Widget _buildSessionStats() {
    final longest = _data['longestSession'] ?? 0;
    final firstPickup = _data['firstPickup'] as String? ?? 'N/A';
    final violations = _data['bedtimeViolationMinutes'] ?? 0;
    final switches = _data['rapidSwitches'] ?? 0;
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Session Analysis',
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            Expanded(
              child: _buildStatCard(
                'Longest Session',
                _formatDuration(longest),
                Icons.timer,
                longest > 120 ? Colors.red : Colors.blue,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: _buildStatCard(
                'First Pickup',
                firstPickup != 'N/A' ? firstPickup.split(' ')[1].substring(0, 5) : 'N/A',
                Icons.access_time,
                Colors.green,
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            Expanded(
              child: _buildStatCard(
                'App Switches',
                '$switches',
                Icons.swap_horiz,
                switches > 20 ? Colors.orange : Colors.purple,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: _buildStatCard(
                'Bedtime Use',
                violations > 0 ? _formatDuration(violations) : 'None',
                Icons.nightlight,
                violations > 0 ? Colors.red : Colors.green,
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildStatCard(String label, String value, IconData icon, Color color) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Column(
        children: [
          Icon(icon, color: color, size: 24),
          const SizedBox(height: 8),
          Text(
            value,
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 16,
              color: color,
            ),
          ),
          Text(
            label,
            style: TextStyle(
              fontSize: 12,
              color: Colors.grey.shade700,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildComparisonStats() {
    final today = _data['totalMinutes'] ?? 0;
    final yesterday = _data['yesterdayTotal'] ?? 0;
    final weeklyAvg = _data['weeklyAverage'] ?? 0;
    
    final vsYesterday = today - yesterday;
    final vsWeekly = today - weeklyAvg;
    
    return Row(
      children: [
        Expanded(
          child: _buildComparisonCard(
            'vs Yesterday',
            vsYesterday,
            yesterday > 0,
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: _buildComparisonCard(
            'vs Weekly Avg',
            vsWeekly,
            weeklyAvg > 0,
          ),
        ),
      ],
    );
  }

  Widget _buildComparisonCard(String label, int difference, bool hasData) {
    final isPositive = difference > 0;
    final color = isPositive ? Colors.red : Colors.green;
    final icon = isPositive ? Icons.arrow_upward : Icons.arrow_downward;
    final text = hasData ? '${difference.abs()} min' : 'No data';
    final subtext = isPositive ? 'More than usual' : 'Less than usual';
    
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.grey.shade50,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        children: [
          Text(label, style: TextStyle(fontSize: 12, color: Colors.grey.shade600)),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (hasData) ...[
                Icon(icon, size: 20, color: color),
                const SizedBox(width: 4),
              ],
              Text(
                text,
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 18,
                  color: hasData ? color : Colors.grey,
                ),
              ),
            ],
          ),
          if (hasData)
            Text(
              subtext,
              style: TextStyle(fontSize: 11, color: Colors.grey.shade600),
            ),
        ],
      ),
    );
  }

  Widget _buildActionButtons() {
    return Column(
      children: [
        SizedBox(
          width: double.infinity,
          child: ElevatedButton.icon(
            onPressed: _shareReportCard,
            icon: const Icon(Icons.share),
            label: const Text('Share Daily Report Card'),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.purple,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            Expanded(
              child: OutlinedButton.icon(
                onPressed: _exportToPDF,
                icon: const Icon(Icons.picture_as_pdf),
                label: const Text('Export PDF'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: OutlinedButton.icon(
                onPressed: () {
                  _loadData(); // Refresh
                },
                icon: const Icon(Icons.sync),
                label: const Text('Sync Data'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }
}